#!/bin/sh

#
# bspwm configuration file
#

#
# Monitors and desktops
#

monitors=$(xrandr -q | grep "\sconnected")

for mon in ${monitors}; do
  bspc monitor ${mon} -d 1 2 3 4 5 6 7 8 9
done

#
# Window border and gaps
#

bspc config border_width 2
bspc config window_gap 8
bspc config top_padding 8
bspc config bottom_padding 8
bspc config left_padding 8
bspc config right_padding 8

#
# Mouse configuration
#

bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#
# Colors
#

bspc config normal_border_color "#202020"
bspc config active_border_color "#202020"
bspc config focused_border_color "#7eaac7"
bspc config presel_feedback_color "#202020"

